### ISSUE TITLE
Leetcode js 全局函数问题

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/LeetCode#1]
感谢蛋哥分享此仓库，学习到很多！有几个问题想咨询一下：

最近发现 [https://leetcode.com/problems/recover-binary-search-tree/](https://leetcode.com/problems/recover-binary-search-tree/) 用[你的代码](https://github.com/Molunerfinn/LeetCode/blob/master/98.validate-binary-search-tree.js)也无法 AC，我也是调试了半天才发现 js 把函数写成全局变量的话貌似会被 Leetcode 提前调用（我改了函数名、变量名也没有有用）？[相关的讨论](https://leetcode.com/problems/binary-tree-tilt/discuss/102353/why-doesnt-this-work-stuck-on-using-global-variable-javascript/105813)

最终通过把所有函数、全局变量定义在 `recoverTree` 内部解决了，[代码](https://github.com/upupming/algorithm/blob/master/leetcode/99.recover-binary-search-tree.js)。但是却发现你的[这个 110 的代码](https://github.com/Molunerfinn/LeetCode/blob/master/110.balanced-binary-tree.js)有全局的函数也是可以 AC 的。

还有一个问题就是，我发现 js 的**输入**特别麻烦，[例子](https://github.com/upupming/algorithm/blob/master/upupming/1047.js)，之前在刷 Codeforces 和 PAT 的时候发现根本难以正确地读取输入（所以打算做做 LeetCode 提升一下 js 算法哈哈），你可有什么建议呢？

十分感谢！

**Comment by Molunerfinn** [comment]
js用var将函数声明为一个全局变量的时候存在变量提升的问题。随便搜了一下文章可供参考：https://www.cnblogs.com/liuhe688/p/5891273.html

所以为了保险，尽量都用 `function a(){}` 来声明函数而不要用 `var a = function (){}`。

如果不理解参考如下代码：

```js
function a () {
  b()
}
var b = function () {}
```

实际上等同于

```js
var b
function a () {
  b() // 此时报错
}
b = function () {}
```

而如果是如下：

```js
function a () {
  b()
}
function b() {}
```
可以简单认为是(虽然不准确，但是意思是这样）：

```js
function b() {}
function a() {
  b()
}
```

这个是js独有的问题。

然后JS输入的问题，其他的环境我只用过牛客的，确实比较蛋疼，所以刷其他平台的只能自己整理一套拿参数的工具函数自己用了。如果leetcode就不存在这个问题，就是树和链表在自测的时候比较麻烦点，其他都比较容易。

**Comment by upupming** [comment]
@Molunerfinn 嗯嗯，我这几天也在学习这里刚看过那篇文章，js 只会提升 `var` 形式的**声明**，但是并**不会提升赋值**。`function a(){}`可以直接整体作为**声明**被提升，[这里](https://www.jianshu.com/p/28ede2f4f30f)也有一篇提到。

但是我感觉这个也不是 Leetcode 所遇到的问题（直接声明和用 `var` 赋值都不行），不清楚它具体是啥架构，我猜测可能是全局变量被污染？？

然后这个输入我感觉就这样啦，勉勉强强可以用着，效率比较低、代码比较冗余。
